version: "3.8"

services:
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
    volumes:
      - ./docker/redis/data:/data

  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

  localstack:
    extends:
      file: docker-compose.base.yml
      service: localstack
    volumes:
      - "./docker/localstack/data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  aws-cli:
    extends:
      file: docker-compose.base.yml
      service: aws-cli
    volumes:
      - ./docker/localstack/cli:/aws

  quadratic-client:
    extends:
      file: docker-compose.base.yml
      service: quadratic-client

  quadratic-api:
    extends:
      file: docker-compose.base.yml
      service: quadratic-api

  quadratic-multiplayer:
    extends:
      file: docker-compose.base.yml
      service: quadratic-multiplayer

  quadratic-files:
    extends:
      file: docker-compose.base.yml
      service: quadratic-files

volumes:
  docker:
    name: docker
