version: "3.8"

services:
  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./docker/redis/d–∞ta:/root/redis
    # command: redis-server --loglevel debug
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: "5s"
    networks:
      - quadratic

volumes:
  docker:

networks:
  quadratic:
