[package]
name = "quadratic-rust-shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonwebtoken = "9.2.0"
reqwest = { version = "0.11.22", features = ["json", "serde_json"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
strum_macros = "0.25.3"
thiserror = "1.0.51"
tokio = { version = "1.34.0", features = ["full"] }
uuid = "1.6.1"

[dev-dependencies]
