name: CI Fast (test)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-core:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Run Rust tests in quadratic-core
      run: |
        cd quadratic-core
        cargo test

  test-client-unit:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Run npm test:ci in quadratic-client
      run: |
        cd quadratic-client
        npm install
        npm run test:unit

  test-client-python:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Test python
      run: |
        pip install -r requirements.txt
        cd quadratic-client
        npm run test:python

  test-api-unit:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Run npm test:ci in quadratic-client
      run: |
        cd quadratic-api
        npm install
        npm run docker:test:ci

  lint-rust:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Run cargo clippy in quadratic-core
      run: |
        cd quadratic-core
        cargo clippy -- -D warnings
  
  lint-client:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Build wasm core
      run: |
        cd quadratic-client
        npm run build:wasm

    - name: Lint quadratic-client
      run: |
        cd quadratic-client
        npm install
        npm run lint:prettier
        npm run lint:eslint
        npm run lint:ts
