name: Lint Check
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache quadratic-core build
        uses: actions/cache@v2
        with:
          path: |
            quadratic-core/target
            quadratic-core/pkg
          key: ${{ runner.os }}-quadratic-core-lint
          restore-keys: |
            ${{ runner.os }}-quadratic-core-lint

      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'npm'
          cache-dependency-path: 'quadratic-client/'

      - name: Update local rust toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Run Clippy
        run: |
          npm run lint:clippy

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build Quadratic
        run: |
          cd quadratic-client
          npm run build:wasm

      - run: |
          cd quadratic-client
          npm config set registry https://registry.npmjs.cf/
      - run: |
          cd quadratic-client
          npm install

      - name: Run Prettier
        run: |
          cd quadratic-client
          npm run lint:prettier

      - name: Run EsLint
        run: |
          cd quadratic-client
          npm run lint:eslint

      - name: Run TypeScript
        run: |
          cd quadratic-client
          npm run lint:ts
