name: Deploy Preview Branch

on:
  pull_request:


# Use runs on `ubuntu-latest-8-cores`. All of our self hosted runners use this tag.
# Our runners pick up jobs first, and if all our runners are being used or are down
# it will automatically back up to using GitHub hosted runners.


jobs:
  multiplayer_preview:
    runs-on: ubuntu-latest-4-cores 
    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: moonrepo/setup-rust@v1
      with:
        components: clippy, llvm-tools-preview
        cache: false
        channel: 'nightly'

    - name: Install pkg-config
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config

    - name: Build quadratic-multiplayer
      run: |
        cd quadratic-multiplayer
        cargo build --release

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: quadratic-multiplayer-x64
    #     path: target/release/quadratic-multiplayer

    - run: cd infra && npm ci

    - run: pulumi config set aws:region us-west-2
    - uses: pulumi/actions@v4
      with:
        work-dir: infra
        command: up
        stack-name: quadratic/quadratic-infra-test-1/preview
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    - name: Set Pulumi Output as Output
      id: set-output
      run: |
        echo "EC2_URL=$(pulumi stack output instancePublicDns)" >> $GITHUB_ENV

    - name: Set up SSH Key
      env:
        EC2_KEY_PEM: ${{ secrets.EC2_KEY_PEM }}
      run: |
        mkdir -p ~/.ssh
        echo "$EC2_KEY_PEM" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Your SSH-based commands here, e.g., scp, ssh

    - name: Transfer Build to EC2
      run: | 
        scp -i ~/.ssh/id_rsa ~/devel/quadratic/quadratic-multiplayer/target/release/quadratic-multiplayer ubuntu@${{ env.EC2_URL }}:/home/ubuntu/

    - name: Restart Application on EC2
      run: |
        ssh -i ~/.ssh/id_rsa ${{ env.EC2_URL }} "sudo systemctl restart quadratic-multiplayer"


  # client_preview:
  #   runs-on: ubuntu-latest-8-cores
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: actions/setup-node@v4
  #     with:
  #       node-version: 18
  #   - name: Set up Rust
  #     uses: moonrepo/setup-rust@v1
  #     with:
  #       cache: false
  #   - uses: jetli/wasm-pack-action@v0.4.0
  #     with:
  #       version: 'latest'

  #   - name: Install Dependencies
  #     run: |
  #       cd quadratic-client
  #       npm install

  #   - name: Build
  #     run: |
  #       cd quadratic-client
  #       npm run build:wasm:javascript
  #       npm run build:wasm:types
  #       npm run build
  #     env:
  #       VITE_ENVIRONMENT: preview
  #       VITE_QUADRATIC_API_URL: https://quadratic-api-dev-pr-${{ github.event.pull_request.number }}.herokuapp.com
  #       VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
  #       VITE_AUTH0_CLIENT_ID: ${{ secrets.VITE_AUTH0_CLIENT_ID }}
  #       VITE_AUTH0_AUDIENCE: ${{ secrets.VITE_AUTH0_AUDIENCE }}
  #       VITE_AUTH0_ISSUER: ${{ secrets.VITE_AUTH0_ISSUER }}
  #       VITE_AUTH0_DOMAIN: ${{ secrets.VITE_AUTH0_DOMAIN }}

    # - name: Deploy to AWS S3
    #   run: aws s3 sync dist s3://quadratic-preview-branches --delete
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # - name: Invalidate CloudFront Distribution
    #   run: aws cloudfront create-invalidation --distribution-id your-distribution-id --paths "/*"
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # - name: Post Deployment URL to PR
    #   if: github.event_name == 'pull_request'
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     DEPLOY_URL: "https://your-cloudfront-distribution-url.com/prs/${{ github.head_ref }}"
    #   run: |
    #     PR_COMMENT="Deployment is ready! 🚀\n\nPreview: $DEPLOY_URL"
    #     PAYLOAD=$(echo '{}' | jq --arg body "$PR_COMMENT" '.body = $body')
    #     COMMENTS_URL=$(jq -r .pull_request.comments_url < "$GITHUB_EVENT_PATH")
    #     curl -s -S -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/json" --data "$PAYLOAD" "$COMMENTS_URL"
