on:
  pull_request:
    types: [closed]

# Use runs on `ubuntu-latest-8-cores`. All of our self hosted runners use this tag.
# Our runners pick up jobs first, and if all our runners are being used or are down
# it will automatically back up to using GitHub hosted runners.

jobs:
  teardown:
    name: Destroy Pulumi Infrastructure Stack
    runs-on: ubuntu-latest-8-cores 
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - uses: pulumi/actions@v4

    - name: Destroy Infrastructure Stack
      working-directory: infra
      run: |
        npm ci
        
        STACK_NAME="preview-pr-${{ env.PR_ID }}"
        pulumi stack select $STACK_NAME
        pulumi config set aws:region us-west-2

        pulumi destroy -y --remove

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        PR_ID: ${{ github.event.pull_request.number }}