name: Unit Tests
on: push

jobs:
  test_unit:
    runs-on: ubuntu-latest-4-cores

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm install
      - run: npm run build:wasm:nodejs
      - run: npm run test:unit:ci
